apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: vmfernandezgpipelinesjavascriptdocker 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: vmfernandezgpipelinesjavascriptdocker 
    spec:
      containers:
        - name: vmfernandezgpipelinesjavascriptdocker 
          image: vfernandezg.azurecr.io/vmfernandezgpipelinesjavascriptdocker 
          ports:
          - containerPort: 8080
